name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  internal-tests:
    name: Internal tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy,rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2022-12-03

      - uses: actions-rs/install@v0.1
        with:
          crate: rust-tools
          use-tool-cache: true

      - uses: Swatinem/rust-cache@v1

      - run: .scripts/internal-tests.sh

  integration-tests:
    container: projectserum/build:v0.26.0
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup default nightly-2022-12-03
      - run: solana config set --url http:localhost:8899
      - run: .scripts/ci.sh
