name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  internal:
    name: Internal tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy,rustfmt
          override: true
          profile: minimal
          toolchain: beta

      - uses: Swatinem/rust-cache@v1

      - run: .scripts/internal-tests.sh
